---
title: MEEPLE BR JOGOS
timezone: America/Sao_Paulo
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: atendimento@meeplebrjogos.com.br
description: A Meeple BR Jogos é uma editora e publicadora de boardgames, nacionais
  e internacionais. Nascida como uma produtora de componentes para jogos, iniciou
  a publicação de jogos em 2016.
baseurl: 
url: 
twitter_username: 
github_username: meeplebr
markdown: kramdown
theme: minima
gems:
- jekyll-feed
- jekyll-admin
exclude:
- Gemfile
- Gemfile.lock
